### ISSUE TITLE
[IDEA] Announce in Talk Forum

### ISSUE THREAD

**Issue by kookma** [benwebber/tiddlywiki-plugins#1]
As there is no discussion section, I write here.

The plugins in https://benwebber.github.io/tiddlywiki-plugins/ are just amazing and worth to be announced in https://talk.tiddlywiki.org/

You introduced very smart solution for tag count, whiteout overwriting the core tiddlers! I just wonder if there is a performance impact or not! but for small number tiddlers e.g. few hundreds to few thousands it showed great performance!

**Comment by benwebber** [comment]
Thanks for the kind words @kookma! I'm a big fan of your work.

These are all plugins that I've extracted out of my own notebook. They're a bit rough right now. I'll announce it on the new talk forum after I improve the documentation site.

**Comment by benwebber** [comment]
Here we go :)

https://talk.tiddlywiki.org/t/announcing-my-plugin-library/5880
