### ISSUE TITLE
Red Screen of Embarassment using Motion plugin

### ISSUE THREAD

**Issue by Marxsal** [benwebber/tiddlywiki-plugins#2]
Hello! The motion plugin has a problem when used with the external js plugin. The author of external js describes the problem and the fix in this post:

https://talk.tiddlywiki.org/t/discussion-how-to-reduce-the-size-of-your-tiddlywiki/5382/32?u=mark_s

Thank you!

**Comment by benwebber** [comment]
Thanks for the bug report. This is fixed in 0.2.1, you can download it here:

https://benwebber.github.io/tiddlywiki-plugins/#motion
